name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Remove
      run: rm -fr .github node_modules .nvmrc .editorconfig .gitignore .prettierrc.js .git

    - uses: actions/upload-artifact@master
      with:
        name: syllable-hyphenator
        path: .

    - name: Zip
      if: startsWith(github.ref, 'refs/tags/')
      run: rsync -av * syllable-hyphenator && zip -r syllable-hyphenator.zip syllable-hyphenator
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: syllable-hyphenator.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
